packages:
  - 'packages/common-types'
  - 'packages/common-functions'
  - 'packages/data-providers'
  - 'packages/database'
  # - 'packages/electron-app'
  - 'packages/logger'
  - 'packages/cli'