/** Declaration file generated by dts-gen */

export = compress_images;

declare function compress_images(input: any, output: any, option: any, findfileop: any, enginejpg: any, enginepng: any, enginesvg: any, enginegif: any, callback: any): any;

